#!/bin/sh

folder=`printf '%s\n' "${PWD##*/}" | tr '[:upper:]' '[:lower:]'`

docker run --rm -it \
  -v /app/node_modules \
  -v /app/prisma-client \
  -v ${PWD}/src:/app \
  -p 4000:4000 \
  --link prisma_nodejs:prisma \
  --network ${folder}_default \
  node:alpine \
  sh
