#!/bin/sh

docker run --rm -it \
  -v /app/node_modules \
  -v /app/generated \
  -v ${PWD}/src:/app \
  -p 4000:4000 \
  --link prisma_nodejs:prisma \
  --network prisma-test_default \
  node:alpine \
  sh
