#!/bin/sh

ip=http:\\/\\/$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' prisma_nodejs)
folder=`printf '%s\n' "${PWD##*/}" | tr '[:upper:]' '[:lower:]'`

docker run --rm -it --name prisma_service \
  -e PRISMA_ENDPOINT=${ip}:4466 \
  -p 4000:4000 \
  --link prisma_nodejs:prisma \
  --network ${folder}_default \
  mbs
